-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."softcartDimDate"
(
    date_id integer NOT NULL,
    date date,
    year smallint,
    quarter smallint,
    quarter_name character varying(2),
    month smallint,
    month_name character varying(16),
    week smallint,
    day smallint,
    weekday character varying(1),
    PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCategory"
(
    category_id integer NOT NULL,
    category_name character varying(64),
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimItem"
(
    item_id integer NOT NULL,
    item_name character varying(64),
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."softcartDimCountry"
(
    country_id smallint NOT NULL,
    country_name character varying(64),
    PRIMARY KEY (country_id)
);

CREATE TABLE IF NOT EXISTS public."softcartFactSales"
(
    order_id integer NOT NULL,
    date_id integer NOT NULL,
    item_id integer NOT NULL,
    category_id integer,
    country_id smallint,
    price smallint NOT NULL,
    CONSTRAINT "orderid_PK" PRIMARY KEY (order_id)
);

ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT "itemid_FK" FOREIGN KEY (item_id)
    REFERENCES public."softcartDimItem" (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT "countryid_FK" FOREIGN KEY (country_id)
    REFERENCES public."softcartDimCountry" (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT "categoryid_FK" FOREIGN KEY (category_id)
    REFERENCES public."softcartDimCategory" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."softcartFactSales"
    ADD CONSTRAINT "dateid_FK" FOREIGN KEY (date_id)
    REFERENCES public."softcartDimDate" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;